### ISSUE TITLE
The training results were good but the test results were poor

### ISSUE THREAD

**Issue by yisampi** [joytsay/livenessDetection#3]
this is the training result.
[INFO] evaluating network...
             precision    recall  f1-score   support

       fake       1.00      0.98      0.99     13633
       real       0.98      1.00      0.99     13913

avg / total       0.99      0.99      0.99     27546

But i use the laptop  camera to test, the image in my cellphone image or video is recognized as real

**Comment by joytsay** [comment]
Looks like you may have overfitted to the training data, try giving more training images or decrease the number of epochs. Keep in mind that this kind of liveness detection is looking at image quality, so if your laptop camera is blurred to begin with, it won't know the difference between blurred real person and blurred fake cellphone image.

**Comment by joytsay** [comment]
p.s When you run runLiveness.bat
you can try out higher confidence (aka -c 0.5->0.8) to get better inference results:
python liveness_demo.py -m liveness.model -l le.pickle -d ./face_detector **_-c 0.8_**
