### ISSUE TITLE
about resnet50 model

### ISSUE THREAD

**Issue by leizhu1989** [joytsay/livenessDetection#6]
hello ！
Is the resnet50 model not open source? I would like to test its effectiveness for videos on mobile phones

**Comment by joytsay** [comment]
yeah i wanted to put the model of github but my LFS is full, so maybe i'll use [google drive](https://drive.google.com/drive/folders/1Uj49JwLSAY4Q4v6UVMNF0u9hobGrJoWC?usp=sharing)
